[[redirects]]
  from = "/*"
  to = "https://zenquotes.io/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"